channels:
  - conda-forge
dependencies:
  - jupyterlab=3.3.1
  - ipykernel
  - python=3.9
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - numpy=1.21.0
  - pandas=1.3.5
  - scipy=1.7.3
  - scikit-learn=1.0.0